import type { ImportColumnSpec, CompositeLookupSpec } from './master-types';

export interface MasterTableSpec {
  title: string;
  table: string;
  orderBy: string;
  selectQuery?: string;
  importEnabled: boolean;
  searchKeys: string[];
  importColumns: ImportColumnSpec[];
  compositeLookups?: CompositeLookupSpec[];
}

export const MASTER_TABLE_SPECS: Record<string, MasterTableSpec> = {
  years: {
    title: 'Years',
    table: 'years',
    orderBy: 'start_date',
    importEnabled: true,
    searchKeys: ['year_label'],
    importColumns: [
      { key: 'year_label', header: 'Year Label', type: 'text', required: true },
      { key: 'start_date', header: 'Start Date', type: 'date', required: true },
      { key: 'end_date', header: 'End Date', type: 'date', required: true },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  designations: {
    title: 'Designations',
    table: 'designations',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'description'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  certificates: {
    title: 'Certificates',
    table: 'certificates',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'description'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'validity_period_months', header: 'Validity (months)', type: 'number' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  csr_partners: {
    title: 'CSR Partners',
    table: 'csr_partners',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'contact_person', 'email', 'mobile', 'city'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'contact_person', header: 'Contact Person', type: 'text' },
      { key: 'email', header: 'Email', type: 'email' },
      { key: 'mobile', header: 'Mobile', type: 'text' },
      { key: 'address', header: 'Address', type: 'textarea' },
      { key: 'city', header: 'City', type: 'text' },
      { key: 'state', header: 'State', type: 'text' },
      { key: 'pincode', header: 'Pincode', type: 'text' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  organisations: {
    title: 'Organisations',
    table: 'organisations',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'city', 'gstin', 'pan'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'address', header: 'Address', type: 'textarea' },
      { key: 'city', header: 'City', type: 'text' },
      { key: 'state', header: 'State', type: 'text' },
      { key: 'pincode', header: 'Pincode', type: 'text' },
      { key: 'gstin', header: 'GSTIN', type: 'text' },
      { key: 'pan', header: 'PAN', type: 'text' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  stakeholders: {
    title: 'Stakeholders',
    table: 'stakeholders',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'contact_person', 'mobile', 'email'],
    importColumns: [
      {
        key: 'category_id',
        header: 'Category',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholder_categories', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'contact_person', header: 'Contact Person', type: 'text' },
      { key: 'mobile', header: 'Mobile', type: 'text' },
      { key: 'email', header: 'Email', type: 'email' },
      { key: 'gstin', header: 'GSTIN', type: 'text' },
      { key: 'pan', header: 'PAN', type: 'text' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  activities: {
    title: 'Activities',
    table: 'activities',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'description'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'unit_of_measurement', header: 'Unit', type: 'text' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  resource_categories: {
    title: 'Resource Categories',
    table: 'resource_categories',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'description'],
    importColumns: [
      { key: 'name', header: 'Category Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      {
        key: 'category_type',
        header: 'Type',
        type: 'select',
        required: true,
        options: [
          { value: 'material', label: 'Material' },
          { value: 'service', label: 'Service' },
        ],
      },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  resources_materials: {
    title: 'Resources',
    table: 'resources_materials',
    orderBy: 'name',
    selectQuery: '*, resource_category:resource_categories(name, category_type)',
    importEnabled: true,
    searchKeys: ['name', 'code', 'description', 'unit_of_measurement'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'unit_of_measurement', header: 'Unit', type: 'text', required: true },
      {
        key: 'category_id',
        header: 'Resource Category',
        type: 'select',
        required: true,
        resolveFrom: {
          table: 'resource_categories',
          valueKey: 'id',
          labelKey: 'name',
          labelSuffixKey: 'category_type',
        },
      },
      { key: 'is_tree_species', header: 'Tree Species', type: 'boolean' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  users: {
    title: 'Users',
    table: 'users',
    orderBy: 'full_name',
    importEnabled: false,
    searchKeys: ['full_name', 'mobile', 'email'],
    importColumns: [
      { key: 'full_name', header: 'Full Name', type: 'text', required: true },
      { key: 'mobile', header: 'Mobile', type: 'text', required: true },
      { key: 'email', header: 'Email', type: 'email' },
      {
        key: 'role',
        header: 'Role',
        type: 'select',
        required: true,
        options: [
          { value: 'admin', label: 'Admin' },
          { value: 'organisation_admin', label: 'Organisation Admin' },
          { value: 'organisation_employee', label: 'Organisation Employee' },
          { value: 'stakeholder', label: 'Stakeholder' },
        ],
      },
      {
        key: 'status',
        header: 'Status',
        type: 'select',
        required: true,
        options: [
          { value: 'active', label: 'Active' },
          { value: 'inactive', label: 'Inactive' },
          { value: 'suspended', label: 'Suspended' },
        ],
      },
    ],
  },
  projects: {
    title: 'Projects',
    table: 'projects',
    orderBy: 'name',
    importEnabled: true,
    selectQuery:
      '*, year:years(year_label), csr_partner:csr_partners(name), organisation:organisations(name)',
    searchKeys: ['name', 'code', 'location', 'district', 'state'],
    importColumns: [
      {
        key: 'year_id',
        header: 'Year',
        type: 'select',
        required: true,
        resolveFrom: { table: 'years', valueKey: 'id', labelKey: 'year_label' },
      },
      {
        key: 'csr_partner_id',
        header: 'CSR Partner',
        type: 'select',
        required: true,
        resolveFrom: { table: 'csr_partners', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'organisation_id',
        header: 'Organisation',
        type: 'select',
        required: true,
        resolveFrom: { table: 'organisations', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'name', header: 'Project Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'total_land_area_acres', header: 'Total Land (acres)', type: 'number', required: true },
      { key: 'total_trees_planned', header: 'Trees Planned', type: 'number', required: true },
      { key: 'budget_amount', header: 'Budget', type: 'number' },
      {
        key: 'status',
        header: 'Status',
        type: 'select',
        options: [
          { value: 'draft', label: 'Draft' },
          { value: 'active', label: 'Active' },
          { value: 'completed', label: 'Completed' },
          { value: 'on_hold', label: 'On Hold' },
          { value: 'cancelled', label: 'Cancelled' },
        ],
      },
      { key: 'start_date', header: 'Start Date', type: 'date' },
      { key: 'end_date', header: 'End Date', type: 'date' },
      { key: 'location', header: 'Location', type: 'text' },
      { key: 'district', header: 'District', type: 'text' },
      { key: 'state', header: 'State', type: 'text' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  project_areas: {
    title: 'Project Areas',
    table: 'project_areas',
    orderBy: 'level',
    importEnabled: true,
    selectQuery:
      '*, project:projects(name, code), parent_area:parent_area_id(name, code)',
    searchKeys: ['name', 'code', 'description', 'project', 'parent_area'],
    importColumns: [
      {
        key: 'project_id',
        header: 'Project',
        type: 'select',
        required: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name', labelSuffixKey: 'code' },
      },
      {
        key: 'parent_area_id',
        header: 'Parent Area Code',
        type: 'select',
        resolveFrom: { table: 'project_areas', valueKey: 'id', labelKey: 'code' },
      },
      { key: 'level', header: 'Level', type: 'number', required: true },
      { key: 'name', header: 'Area Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'land_area_acres', header: 'Land Area (acres)', type: 'number', required: true },
      { key: 'trees_planned', header: 'Trees Planned', type: 'number', required: true },
      { key: 'trees_planted', header: 'Trees Planted', type: 'number' },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  project_activities: {
    title: 'Project Activities',
    table: 'project_activities',
    orderBy: 'planned_start_date',
    selectQuery:
      '*, project:projects(name, code), activity:activities(id, name, code), project_area:project_areas(id, name, code)',
    importEnabled: true,
    searchKeys: ['planned_quantity', 'project', 'activity', 'project_area'],
    importColumns: [
      {
        key: 'project_id',
        header: 'Project',
        type: 'select',
        required: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'activity_id',
        header: 'Activity',
        type: 'select',
        required: true,
        resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'project_area_id',
        header: 'Project Area Code',
        type: 'select',
        resolveFrom: { table: 'project_areas', valueKey: 'id', labelKey: 'code' },
      },
      { key: 'planned_quantity', header: 'Planned Quantity', type: 'number' },
      { key: 'planned_start_date', header: 'Planned Start', type: 'date' },
      { key: 'planned_end_date', header: 'Planned End', type: 'date' },
      { key: 'budget_amount', header: 'Budget', type: 'number' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  project_user_access: {
    title: 'Project User Access',
    table: 'project_user_access',
    orderBy: 'created_at',
    importEnabled: true,
    selectQuery: '*, project:projects(name, code), user:users(full_name, mobile, email)',
    searchKeys: ['project', 'user'],
    importColumns: [
      {
        key: 'project_id',
        header: 'Project',
        type: 'select',
        required: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'user_id',
        header: 'User Mobile',
        type: 'select',
        required: true,
        resolveFrom: { table: 'users', valueKey: 'id', labelKey: 'mobile' },
      },
    ],
  },
  stakeholder_categories: {
    title: 'Stakeholder Categories',
    table: 'stakeholder_categories',
    orderBy: 'name',
    importEnabled: true,
    searchKeys: ['name', 'code', 'description'],
    importColumns: [
      { key: 'name', header: 'Name', type: 'text', required: true },
      { key: 'code', header: 'Code', type: 'text' },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  stakeholder_resources: {
    title: 'Stakeholder Resources',
    table: 'stakeholder_resources',
    orderBy: 'created_at',
    selectQuery: '*, stakeholder:stakeholders(name, code), resource:resources_materials(name, code)',
    importEnabled: true,
    searchKeys: ['stakeholder', 'resource'],
    importColumns: [
      {
        key: 'stakeholder_id',
        header: 'Stakeholder',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholders', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'resource_id',
        header: 'Resource',
        type: 'select',
        required: true,
        resolveFrom: { table: 'resources_materials', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  stakeholder_supply_rates: {
    title: 'Stakeholder Supply Rates',
    table: 'stakeholder_supply_rates',
    orderBy: 'effective_from',
    selectQuery:
      '*, stakeholder:stakeholders(name, code), resource:resources_materials(name, code), project:projects(name, code)',
    importEnabled: true,
    searchKeys: ['stakeholder', 'resource', 'project'],
    importColumns: [
      {
        key: 'stakeholder_id',
        header: 'Stakeholder',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholders', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'resource_id',
        header: 'Resource',
        type: 'select',
        required: true,
        resolveFrom: { table: 'resources_materials', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'project_id',
        header: 'Project',
        type: 'select',
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'rate', header: 'Rate', type: 'number', required: true },
      { key: 'effective_from', header: 'Effective From', type: 'date', required: true },
      { key: 'effective_to', header: 'Effective To', type: 'date' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  stakeholder_category_access_rights: {
    title: 'Stakeholder Access Rights',
    table: 'stakeholder_category_access_rights',
    orderBy: 'module_name',
    selectQuery: '*, category:stakeholder_categories(name)',
    importEnabled: true,
    searchKeys: ['module_name'],
    importColumns: [
      {
        key: 'category_id',
        header: 'Stakeholder Category',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholder_categories', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'module_name', header: 'Module', type: 'text', required: true },
      { key: 'can_view', header: 'Can View', type: 'boolean' },
      { key: 'can_create', header: 'Can Create', type: 'boolean' },
      { key: 'can_edit', header: 'Can Edit', type: 'boolean' },
      { key: 'can_delete', header: 'Can Delete', type: 'boolean' },
      { key: 'can_approve', header: 'Can Approve', type: 'boolean' },
    ],
  },
  organisation_contacts: {
    title: 'Organisation Contacts',
    table: 'organisation_contacts',
    orderBy: 'name',
    selectQuery: '*, organisation:organisations(name, code)',
    importEnabled: true,
    searchKeys: ['name', 'email', 'mobile'],
    importColumns: [
      {
        key: 'organisation_id',
        header: 'Organisation',
        type: 'select',
        required: true,
        resolveFrom: { table: 'organisations', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'name', header: 'Contact Name', type: 'text', required: true },
      { key: 'designation', header: 'Designation', type: 'text' },
      { key: 'email', header: 'Email', type: 'email' },
      { key: 'mobile', header: 'Mobile', type: 'text' },
      { key: 'is_primary', header: 'Primary Contact', type: 'boolean' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  organisation_certificates: {
    title: 'Organisation Certificates',
    table: 'organisation_certificates',
    orderBy: 'expiry_date',
    selectQuery: '*, organisation:organisations(name, code), certificate:certificates(name)',
    importEnabled: true,
    searchKeys: ['certificate_number'],
    importColumns: [
      {
        key: 'organisation_id',
        header: 'Organisation',
        type: 'select',
        required: true,
        resolveFrom: { table: 'organisations', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'certificate_id',
        header: 'Certificate Type',
        type: 'select',
        resolveFrom: { table: 'certificates', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'certificate_number', header: 'Certificate Number', type: 'text' },
      { key: 'issue_date', header: 'Issue Date', type: 'date' },
      { key: 'expiry_date', header: 'Expiry Date', type: 'date' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  organisation_employees: {
    title: 'Organisation Employees',
    table: 'organisation_employees',
    orderBy: 'full_name',
    selectQuery: '*, organisation:organisations(name, code), designation:designations(name)',
    importEnabled: true,
    searchKeys: ['full_name', 'employee_code', 'mobile', 'email'],
    importColumns: [
      {
        key: 'organisation_id',
        header: 'Organisation',
        type: 'select',
        required: true,
        resolveFrom: { table: 'organisations', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'employee_code', header: 'Employee Code', type: 'text', required: true },
      { key: 'full_name', header: 'Full Name', type: 'text', required: true },
      {
        key: 'designation_id',
        header: 'Designation',
        type: 'select',
        resolveFrom: { table: 'designations', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'mobile', header: 'Mobile', type: 'text' },
      { key: 'email', header: 'Email', type: 'email' },
      { key: 'date_of_joining', header: 'Date of Joining', type: 'date' },
      { key: 'basic_salary', header: 'Basic Salary', type: 'number' },
      { key: 'gross_salary', header: 'Gross Salary', type: 'number' },
      { key: 'allow_app_login', header: 'Allow App Login', type: 'boolean' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  activity_resource_requirements: {
    title: 'Activity Resource Requirements',
    table: 'activity_resource_requirements',
    orderBy: 'created_at',
    selectQuery:
      '*, project_activity:project_activities(project_id, project:projects(name), activity:activities(name), project_area:project_areas(name)), resource:resources_materials(name, code)',
    importEnabled: true,
    searchKeys: ['project_activity', 'resource'],
    compositeLookups: [
      {
        targetKey: 'project_activity_id',
        table: 'project_activities',
        matchFields: [
          { importKey: '_project', rowField: 'project_id', resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' } },
          { importKey: '_activity', rowField: 'activity_id', resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' } },
        ],
      },
    ],
    importColumns: [
      {
        key: '_project',
        header: 'Project',
        type: 'select',
        required: true,
        importOnly: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: '_activity',
        header: 'Activity',
        type: 'select',
        required: true,
        importOnly: true,
        resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'resource_id',
        header: 'Resource',
        type: 'select',
        required: true,
        resolveFrom: { table: 'resources_materials', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'required_quantity', header: 'Required Quantity', type: 'number', required: true },
      { key: 'unit_rate', header: 'Unit Rate', type: 'number' },
    ],
  },
  activity_contractor_allocations: {
    title: 'Activity Contractor Allocations',
    table: 'activity_contractor_allocations',
    orderBy: 'start_date',
    selectQuery:
      '*, project_activity:project_activities(project_id, project:projects(name), activity:activities(name), project_area:project_areas(name)), stakeholder:stakeholders(name, code)',
    importEnabled: true,
    searchKeys: ['project_activity', 'stakeholder'],
    compositeLookups: [
      {
        targetKey: 'project_activity_id',
        table: 'project_activities',
        matchFields: [
          { importKey: '_project', rowField: 'project_id', resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' } },
          { importKey: '_activity', rowField: 'activity_id', resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' } },
        ],
      },
    ],
    importColumns: [
      {
        key: '_project',
        header: 'Project',
        type: 'select',
        required: true,
        importOnly: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: '_activity',
        header: 'Activity',
        type: 'select',
        required: true,
        importOnly: true,
        resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'stakeholder_id',
        header: 'Stakeholder',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholders', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'allocated_quantity', header: 'Allocated Quantity', type: 'number' },
      { key: 'rate', header: 'Rate', type: 'number' },
      { key: 'start_date', header: 'Start Date', type: 'date' },
      { key: 'end_date', header: 'End Date', type: 'date' },
      { key: 'is_active', header: 'Active', type: 'boolean' },
    ],
  },
  work_contracts: {
    title: 'Work Contracts',
    table: 'work_contracts',
    orderBy: 'contract_date',
    selectQuery: '*, project:projects(name, code), stakeholder:stakeholders(name, code)',
    importEnabled: true,
    searchKeys: ['contract_number', 'project', 'stakeholder'],
    importColumns: [
      {
        key: 'project_id',
        header: 'Project',
        type: 'select',
        required: true,
        resolveFrom: { table: 'projects', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'stakeholder_id',
        header: 'Stakeholder',
        type: 'select',
        required: true,
        resolveFrom: { table: 'stakeholders', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'contract_number', header: 'Contract Number', type: 'text' },
      { key: 'contract_date', header: 'Contract Date', type: 'date', required: true },
      { key: 'start_date', header: 'Start Date', type: 'date' },
      { key: 'end_date', header: 'End Date', type: 'date' },
      { key: 'total_value', header: 'Total Value', type: 'number' },
      {
        key: 'status',
        header: 'Status',
        type: 'select',
        options: [
          { value: 'draft', label: 'Draft' },
          { value: 'pending', label: 'Pending' },
          { value: 'approved', label: 'Approved' },
          { value: 'rejected', label: 'Rejected' },
          { value: 'completed', label: 'Completed' },
        ],
      },
      { key: 'terms_and_conditions', header: 'Terms & Conditions', type: 'textarea' },
    ],
  },
  work_contract_items: {
    title: 'Work Contract Items',
    table: 'work_contract_items',
    orderBy: 'created_at',
    selectQuery:
      '*, contract:work_contracts(contract_number, project:projects(name)), resource:resources_materials(name, code), activity:activities(name, code)',
    importEnabled: true,
    searchKeys: ['description', 'contract'],
    importColumns: [
      {
        key: 'contract_id',
        header: 'Contract Number',
        type: 'select',
        required: true,
        resolveFrom: { table: 'work_contracts', valueKey: 'id', labelKey: 'contract_number' },
      },
      {
        key: 'resource_id',
        header: 'Resource',
        type: 'select',
        resolveFrom: { table: 'resources_materials', valueKey: 'id', labelKey: 'name' },
      },
      {
        key: 'activity_id',
        header: 'Activity',
        type: 'select',
        resolveFrom: { table: 'activities', valueKey: 'id', labelKey: 'name' },
      },
      { key: 'description', header: 'Description', type: 'textarea' },
      { key: 'quantity', header: 'Quantity', type: 'number' },
      { key: 'unit_rate', header: 'Unit Rate', type: 'number' },
      { key: 'total_amount', header: 'Total Amount', type: 'number' },
    ],
  },
};

export function getMasterTableSpec(table: string): MasterTableSpec | null {
  return MASTER_TABLE_SPECS[table] ?? null;
}
